CREATE TABLE `book` (
   `BOOK_NO` varchar(8) NOT NULL,
   `BOOK_NM` varchar(100) NOT NULL,
   `BOOK_DESC` varchar(3000) NOT NULL,
   `BOOK_PRICE` mediumint NOT NULL,
   `BOOK_STOCK` smallint NOT NULL,
   `BOOK_IMG` varchar(1000) DEFAULT NULL,
   `BOOK_PUB` varchar(60) NOT NULL,
   `BOOK_AUTHOR` varchar(60) NOT NULL,
   `BOOK_PUB_DATE` date NOT NULL,
   `BOOK_ISBN` varchar(20) DEFAULT NULL,
   `BOOK_PAGE` smallint DEFAULT NULL,
   PRIMARY KEY (`BOOK_NO`),
   UNIQUE KEY `BOOK_ISBN` (`BOOK_ISBN`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
 
 CREATE TABLE `member` (
   `MEM_NO` mediumint NOT NULL AUTO_INCREMENT,
   `MEM_UID` varchar(15) NOT NULL,
   `MEM_PWD` varchar(20) NOT NULL,
   `MEM_NM` varchar(15) NOT NULL,
   `MEM_PHONENO` varchar(11) NOT NULL,
   `MEM_ADDR1` varchar(300) NOT NULL,
   `MEM_ADDR2` varchar(300) NOT NULL,
   `MEM_ADDR3` varchar(300) NOT NULL,
   `MEM_EMAIL` varchar(50) NOT NULL,
   `MEM_MILEAGE` mediumint DEFAULT '0',
   `IS_ADMIN` char(1) DEFAULT '0',
   `ACCESSIBLE` char(1) DEFAULT '1',
   PRIMARY KEY (`MEM_NO`),
   UNIQUE KEY `MEM_UID` (`MEM_UID`),
   UNIQUE KEY `MEM_EMAIL` (`MEM_EMAIL`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
 
 CREATE TABLE `cart` (
   `CART_NO` varchar(10) NOT NULL,
   `MEM_NO` mediumint DEFAULT NULL,
   `BOOK_NO` varchar(8) DEFAULT NULL,
   `CART_QTY` smallint NOT NULL,
   PRIMARY KEY (`CART_NO`),
   KEY `FK_MEMBER_TO_CART_1` (`MEM_NO`),
   KEY `FK_BOOK_TO_CART_1` (`BOOK_NO`),
   CONSTRAINT `FK_BOOK_TO_CART_1` FOREIGN KEY (`BOOK_NO`) REFERENCES `book` (`BOOK_NO`),
   CONSTRAINT `FK_MEMBER_TO_CART_1` FOREIGN KEY (`MEM_NO`) REFERENCES `member` (`MEM_NO`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
 
 CREATE TABLE `faq` (
   `FAQ_NO` mediumint NOT NULL AUTO_INCREMENT,
   `FAQ_CATE` char(1) NOT NULL,
   `FAQ_TITLE` varchar(100) NOT NULL,
   `FAQ_CONTNET` varchar(3000) NOT NULL,
   PRIMARY KEY (`FAQ_NO`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
 
 CREATE TABLE `notice` (
   `NOTI_NO` mediumint NOT NULL AUTO_INCREMENT,
   `NOTI_TITLE` varchar(100) NOT NULL,
   `NOTI_CONTNET` varchar(3000) NOT NULL,
   `NOTI_DATE` datetime NOT NULL,
   PRIMARY KEY (`NOTI_NO`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
 
 CREATE TABLE `no_mem_orders` (
   `ORDERS_NO` varchar(10) NOT NULL,
   `BOOK_NO` varchar(8) DEFAULT NULL,
   `ORDERS_NM` varchar(15) NOT NULL,
   `ORDERS_PHONENO` varchar(11) NOT NULL,
   `ORDERS_ADDR1` varchar(300) NOT NULL,
   `ORDERS_ADDR2` varchar(300) NOT NULL,
   `ORDERS_ADDR3` varchar(300) NOT NULL,
   `ORDERS_DATE` datetime NOT NULL,
   `ORDERS_QTY` smallint NOT NULL,
   `ORDERS_STATUS` char(1) DEFAULT '1',
   PRIMARY KEY (`ORDERS_NO`),
   KEY `FK_BOOK_TO_NO_MEM_ORDER_1` (`BOOK_NO`),
   CONSTRAINT `FK_BOOK_TO_NO_MEM_ORDER_1` FOREIGN KEY (`BOOK_NO`) REFERENCES `book` (`BOOK_NO`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
 
 CREATE TABLE `no_mem_refund` (
   `REFUND_NO` varchar(10) NOT NULL,
   `ORDERS_NO` varchar(8) DEFAULT NULL,
   `REFUND_DESC` varchar(3000) NOT NULL,
   `REFUND_STATUS` char(1) DEFAULT '1',
   PRIMARY KEY (`REFUND_NO`),
   KEY `FK_NO_MEM_ORDER_TO_NO_MEM_REFUND_1` (`ORDERS_NO`),
   CONSTRAINT `FK_NO_MEM_ORDER_TO_NO_MEM_REFUND_1` FOREIGN KEY (`ORDERS_NO`) REFERENCES `no_mem_orders` (`ORDERS_NO`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
 
 CREATE TABLE `orders` (
   `ORDERS_NO` varchar(10) NOT NULL,
   `MEM_NO` mediumint DEFAULT NULL,
   `BOOK_NO` varchar(8) DEFAULT NULL,
   `ORDERS_NM` varchar(15) NOT NULL,
   `ORDERS_PHONENO` varchar(11) NOT NULL,
   `ORDERS_ADDR1` varchar(300) NOT NULL,
   `ORDERS_ADDR2` varchar(300) NOT NULL,
   `ORDERS_ADDR3` varchar(300) NOT NULL,
   `ORDERS_DATE` datetime NOT NULL,
   `ORDERS_QTY` smallint NOT NULL,
   `ORDERS_STATUS` char(1) DEFAULT '1',
   PRIMARY KEY (`ORDERS_NO`),
   KEY `FK_MEMBER_TO_ORDERS_1` (`MEM_NO`),
   KEY `FK_BOOK_TO_ORDERS_1` (`BOOK_NO`),
   CONSTRAINT `FK_BOOK_TO_ORDERS_1` FOREIGN KEY (`BOOK_NO`) REFERENCES `book` (`BOOK_NO`),
   CONSTRAINT `FK_MEMBER_TO_ORDERS_1` FOREIGN KEY (`MEM_NO`) REFERENCES `member` (`MEM_NO`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
 
 CREATE TABLE `refund` (
   `REFUND_NO` varchar(10) NOT NULL,
   `ORDERS_NO` varchar(10) DEFAULT NULL,
   `REFUND_DESC` varchar(3000) DEFAULT NULL,
   `REFUND_STATUS` char(1) DEFAULT '1',
   PRIMARY KEY (`REFUND_NO`),
   KEY `FK_ORDERS_TO_REFUND_1` (`ORDERS_NO`),
   CONSTRAINT `FK_ORDERS_TO_REFUND_1` FOREIGN KEY (`ORDERS_NO`) REFERENCES `orders` (`ORDERS_NO`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
 
 CREATE TABLE `review` (
   `REV_NO` mediumint NOT NULL AUTO_INCREMENT,
   `MEM_NO` mediumint DEFAULT NULL,
   `BOOK_NO` varchar(8) DEFAULT NULL,
   `REV_TITLE` varchar(100) NOT NULL,
   `REV_CONTENT` varchar(3000) NOT NULL,
   `REV_RATING` tinyint NOT NULL,
   `REV_DATE` datetime NOT NULL,
   PRIMARY KEY (`REV_NO`),
   KEY `FK_MEMBER_TO_REVIEW_1` (`MEM_NO`),
   KEY `FK_BOOK_TO_REVIEW_1` (`BOOK_NO`),
   CONSTRAINT `FK_BOOK_TO_REVIEW_1` FOREIGN KEY (`BOOK_NO`) REFERENCES `book` (`BOOK_NO`),
   CONSTRAINT `FK_MEMBER_TO_REVIEW_1` FOREIGN KEY (`MEM_NO`) REFERENCES `member` (`MEM_NO`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
 
 CREATE TABLE `rev_cmt` (
   `CMT_NO` mediumint NOT NULL AUTO_INCREMENT,
   `REV_NO` mediumint DEFAULT NULL,
   `MEM_NO` mediumint DEFAULT NULL,
   `CMT_CONTENT` varchar(1000) NOT NULL,
   `CMT_DATE` datetime NOT NULL,
   PRIMARY KEY (`CMT_NO`),
   KEY `FK_REVIEW_TO_REV_CMT_1` (`REV_NO`),
   KEY `FK_MEMBER_TO_REV_CMT_1` (`MEM_NO`),
   CONSTRAINT `FK_MEMBER_TO_REV_CMT_1` FOREIGN KEY (`MEM_NO`) REFERENCES `member` (`MEM_NO`),
   CONSTRAINT `FK_REVIEW_TO_REV_CMT_1` FOREIGN KEY (`REV_NO`) REFERENCES `review` (`REV_NO`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
 
 CREATE TABLE `qna_q` (
   `Q_NO` mediumint NOT NULL AUTO_INCREMENT,
   `MEM_NO` mediumint DEFAULT NULL,
   `Q_TITLE` varchar(100) NOT NULL,
   `Q_CONTENT` varchar(3000) NOT NULL,
   `Q_DATE` datetime NOT NULL,
   `Q_PWD` varchar(20) NOT NULL,
   `Q_CATE` char(1) NOT NULL,
   `ACCESS_LEVEL` char(1) NOT NULL,
   PRIMARY KEY (`Q_NO`),
   KEY `FK_MEMBER_TO_QNA_Q_1` (`MEM_NO`),
   CONSTRAINT `FK_MEMBER_TO_QNA_Q_1` FOREIGN KEY (`MEM_NO`) REFERENCES `member` (`MEM_NO`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
 
 CREATE TABLE `qna_a` (
   `A_NO` mediumint NOT NULL AUTO_INCREMENT,
   `Q_NO` mediumint DEFAULT NULL,
   `MEM_NO` mediumint DEFAULT NULL,
   `A_CONTENT` varchar(3000) NOT NULL,
   `A_DATE` datetime NOT NULL,
   PRIMARY KEY (`A_NO`),
   KEY `FK_QNA_TO_QNA_A_1` (`Q_NO`),
   KEY `FK_MEMBER_TO_QNA_A_1` (`MEM_NO`),
   CONSTRAINT `FK_MEMBER_TO_QNA_A_1` FOREIGN KEY (`MEM_NO`) REFERENCES `member` (`MEM_NO`),
   CONSTRAINT `FK_QNA_TO_QNA_A_1` FOREIGN KEY (`Q_NO`) REFERENCES `qna_q` (`Q_NO`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;